version: '3'
services:
  admin:
    build: ./admin
    ports:
      - "5000:5000"
    networks:
      - qa_assisment_default

  user:
    build: ./user
    ports:
      - "5001:5000"
    networks:
      - qa_assisment_default

networks:
  qa_assisment_default:
    driver: bridge
